server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
    healthCheck:
      enable: false #开启健康检查
  instance:
    lease-renewal-interval-in-seconds: 30  #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 90  #续约更新时间间隔（默认30秒）
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: mamahao                  # 配置登录的账号是user
    password: mamahao123       # 配置登录的密码是password123