spring:
  application:
    name: cloud-config-server



  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/banchunchun/cloud-config-repo.git
          username:    #你的git 帐号
          password:    #你的git密码
          clone-on-start: true
          search-paths: ['{application}','{application}/{profile}']