spring:
  application:
    name: cloud-discovery-server
management:
  security:
    enabled: true
    roles: ADMIN
security:
  basic:
    enabled: false
  user:
    name: banchun
    password: banchun
    role: ADMIN
eureka:
  server:
    registry-sync-retry-wait-ms: 500
    a-s-g-cache-expiry-timeout-ms: 60000
    eviction-interval-timer-in-ms: 30000
    peer-eureka-nodes-update-interval-ms: 15000
    renewal-threshold-update-interval-ms: 30000
    wait-time-in-ms-when-sync-empty: 0

  environment: ${spring.profiles.active}

  datacenter: hz

