spring:
  profiles:
    active: dev
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  datacenter: office
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000 #清理间隔 （默认60*1000）
  client:
    register-with-eureka: false #是否将自己注册到服务器
    fetch-registry: false       #是否从Eureka Server获取注册信息，集群时需要设置为true
    service-url:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/   #置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔


#management:
#  context-path: /admin
endpoints:
  refresh:
    enabled: true
  shutdown:
    enabled: true
  restart:
    enabled: true
  metrics:
    enabled: true